### ISSUE TITLE
Объеденить инпуты

### ISSUE THREAD

**Issue by Lacsw** [physical-activity/physical-activity-frontend#19]
У нас есть 2 почти одинаковых компонента инпута: Input и RegisterInput

Нужно попробовать объеденить их в один и избавиться от дублирования.

**Comment by AndreySaveliev** [comment]
Удалил компонент registerInput. Оставил компонент Input. Стили самой формы трогать не стал. Логику форму регистрации оставил прежней, но с поправками, чтобы корректно работало с компонентом Input.
